name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # Install dependencies (including testing and linting tools)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 black

      # Run linting checks
      - name: Run lint checks
        run: |
          flake8 .
          black --check .

      # Run unit tests with coverage (fail if coverage < 80%)
      - name: Run tests with coverage
        run: |
          pytest --cov=app \
                 --cov-report=term-missing \
                 --cov-fail-under=50               
